name: Validate against JSON schemas

on:
  pull_request:
    paths:
      - "**/*.json"
  workflow_dispatch:
  

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: lts/krypton

      - run: npm install -g ajv-cli

      - name: Validate device types
        run: |
          ajv validate \
            -s schemas/devicetype.schema.json \
            -d "devicetypes/**/*.json" \
            --spec=draft2020 \
            --all-errors

      - name: Validate module types
        run: |
          ajv validate \
            -s schemas/moduletype.schema.json \
            -d "moduletypes/**/*.json" \
            --spec=draft2020 \
            --all-errors
